/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jreserve.data.dataexplorer;

import java.util.HashMap;
import java.util.Map;
import org.jreserve.project.entities.Project;
import org.jreserve.resources.ToolBarButton;
import org.jreserve.resources.textfieldfilters.IntegerFilter;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.util.ImageUtilities;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd = "-//org.jreserve.data.dataexplorer//DataExplorer//EN",
    autostore = false
)
@TopComponent.Description(
    preferredID = "DataExplorerTopComponent",
    iconBase = "resources/database.png", 
    persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(
    mode = "explorer", 
    openAtStartup = false
)
@Messages({
    "LBL.DataExplorerTopComponent.NumberOfRows=rows per page:"
})
public final class DataExplorerTopComponent extends TopComponent {

    private static Map<Long, DataExplorerTopComponent> explorers = new HashMap<Long, DataExplorerTopComponent>();
    
    public static DataExplorerTopComponent getComponent(Project project) {
        DataExplorerTopComponent explorer = explorers.get(project.getId());
        if(explorer == null) {
            explorer = new DataExplorerTopComponent(project);
            explorers.put(project.getId(), explorer);
        }
        return explorer;
    }
    
    private final static String FIRST_PAGE = "resources/resultset_first.png";
    private final static String PREVIOUS_PAGE = "resources/resultset_previous.png";
    private final static String NEXT_PAGE = "resources/resultset_next.png";
    private final static String LAST_PAGE = "resources/resultset_last.png";
    private final static int NUMBER_OF_ROWS = 25;
    
    private Project project;
    
    public DataExplorerTopComponent() {
    }
    
    public DataExplorerTopComponent(Project project) {
        this.project = project;
        initComponents();
        setName(project.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jComboBox1 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        firstPageButton = new ToolBarButton(ImageUtilities.loadImageIcon(FIRST_PAGE, false));
        prevPageButton = new ToolBarButton(ImageUtilities.loadImageIcon(PREVIOUS_PAGE, false));
        nextPageButton = new ToolBarButton(ImageUtilities.loadImageIcon(NEXT_PAGE, false));
        lastPageButton = new ToolBarButton(ImageUtilities.loadImageIcon(LAST_PAGE, false));
        rowPerPAgeLabel = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        rowPerPageText = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jSeparator2 = new javax.swing.JToolBar.Separator();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        tableScroll = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(100, 18));
        jComboBox1.setMinimumSize(new java.awt.Dimension(100, 18));
        jComboBox1.setPreferredSize(new java.awt.Dimension(100, 18));
        jToolBar1.add(jComboBox1);
        jToolBar1.add(jSeparator1);

        org.openide.awt.Mnemonics.setLocalizedText(firstPageButton, null);
        firstPageButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        firstPageButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(firstPageButton);

        org.openide.awt.Mnemonics.setLocalizedText(prevPageButton, null);
        prevPageButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        prevPageButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(prevPageButton);

        org.openide.awt.Mnemonics.setLocalizedText(nextPageButton, null);
        nextPageButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextPageButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(nextPageButton);

        org.openide.awt.Mnemonics.setLocalizedText(lastPageButton, null);
        lastPageButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lastPageButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(lastPageButton);

        org.openide.awt.Mnemonics.setLocalizedText(rowPerPAgeLabel, Bundle.LBL_DataExplorerTopComponent_NumberOfRows());
        jToolBar1.add(rowPerPAgeLabel);
        jToolBar1.add(filler2);

        rowPerPageText.setColumns(3);
        rowPerPageText.setDocument(new IntegerFilter());
        rowPerPageText.setText(""+NUMBER_OF_ROWS);
        rowPerPageText.setMaximumSize(new java.awt.Dimension(30, 18));
        rowPerPageText.setMinimumSize(new java.awt.Dimension(30, 18));
        rowPerPageText.setPreferredSize(new java.awt.Dimension(30, 18));
        jToolBar1.add(rowPerPageText);
        jToolBar1.add(filler3);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(filler4);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScroll.setViewportView(table);

        add(tableScroll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private org.jreserve.resources.ToolBarButton firstPageButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private org.jreserve.resources.ToolBarButton lastPageButton;
    private org.jreserve.resources.ToolBarButton nextPageButton;
    private org.jreserve.resources.ToolBarButton prevPageButton;
    private javax.swing.JLabel rowPerPAgeLabel;
    private javax.swing.JTextField rowPerPageText;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableScroll;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        explorers.remove(project.getId());
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
