package org.jreserve.oracledatabase.opendialog;

import javax.swing.JPanel;
import javax.swing.JTextField;
import org.openide.util.NbBundle.Messages;

@Messages({
    "CTL_stepTwo=Testing connection",
    "CTL_nameLabel=Name:",
    "CTL_passLabel=Password:",
    "CTL_progressText=Testing connection..."
})
final class OpenDialogVisualPanel2 extends JPanel {

    public OpenDialogVisualPanel2() {
        initComponents();
    }

    @Override
    public String getName() {
        return Bundle.CTL_stepTwo();
    }

    String getUserName() {
        return escapeTextField(nameText);
    }
    
    private String escapeTextField(JTextField textField) {
        String str = textField.getText();
        if(str == null || str.trim().length()==0)
            return null;
        return str;
    }
    
    void setUserName(String userName) {
        nameText.setText(userName);
    }
    
    String getPassword() {
        char[] c = passText.getPassword();
        String pass = (c==null || c.length==0)? null : new String(c);
        if(pass != null && pass.trim().length()==0)
            return null;
        return pass;
    }
    
    void startCreatingDb() {
        pBar.setIndeterminate(true);
        pBar.setVisible(true);
        pBarLabel.setVisible(true);
    }
    
    void finishCreatingDb() {
        pBar.setIndeterminate(false);
        pBar.setVisible(false);
        pBarLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        passText = new javax.swing.JPasswordField();
        passLabel = new javax.swing.JLabel();
        pBarLabel = new javax.swing.JLabel();
        pBar = new javax.swing.JProgressBar();

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, Bundle.CTL_nameLabel());

        nameText.setText(org.openide.util.NbBundle.getMessage(OpenDialogVisualPanel2.class, "OpenDialogVisualPanel2.nameText.text")); // NOI18N

        passText.setText(org.openide.util.NbBundle.getMessage(OpenDialogVisualPanel2.class, "OpenDialogVisualPanel2.passText.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(passLabel, Bundle.CTL_passLabel());

        org.openide.awt.Mnemonics.setLocalizedText(pBarLabel, Bundle.CTL_progressText());
        pBarLabel.setVisible(false);

        pBar.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameText)
                            .addComponent(passText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pBarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 234, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel)
                    .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(pBarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JProgressBar pBar;
    private javax.swing.JLabel pBarLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passText;
    // End of variables declaration//GEN-END:variables
}
