package org.jreserve.audit.global;

import org.jreserve.audit.AuditedEntity;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

@ConvertAsProperties(
    dtd = "-//org.jreserve.audit.global//GlobalAuditor//EN",
    autostore = false
)
@TopComponent.Description(
    preferredID = "org.jreserve.audit.global.GlobalAuditorTopComponent",
    iconBase = "resources/audit.png",
    persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(
    mode = "editor", 
    openAtStartup = false
)
@ActionID(
    category = "Window", 
    id = "org.jreserve.audit.global.GlobalAuditorTopComponent"
)
@ActionReference(
    path = "Menu/Window",
    position = 460
)
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_GlobalAuditorAction",
    preferredID = "GlobalAuditorTopComponent"
)
@Messages({
    "CTL_GlobalAuditorAction=Global Auditor",
    "CTL_GlobalAuditorTopComponent=Global Auditor Window"
})
public final class GlobalAuditorTopComponent extends TopComponent implements ExplorerManager.Provider {

    private final static ExplorerManager em = new ExplorerManager();

    public GlobalAuditorTopComponent() {
        initComponents();
        setName(Bundle.CTL_GlobalAuditorTopComponent());
        initializeTree();
    }

    
    private void initializeTree() {
        AuditedEntity root = new AuditedEntity(null, "ROOT", null);
        em.setRootContext(new AuditedEntityNode(root));
        treeView.setRootVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        treeScroll = new javax.swing.JScrollPane();
        treeView = new org.openide.explorer.view.BeanTreeView();
        tableScroll = new javax.swing.JScrollPane();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(150);

        treeScroll.setViewportView(treeView);

        jSplitPane1.setLeftComponent(treeScroll);
        jSplitPane1.setRightComponent(tableScroll);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JScrollPane tableScroll;
    private javax.swing.JScrollPane treeScroll;
    private org.openide.explorer.view.BeanTreeView treeView;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
    }

    void writeProperties(java.util.Properties p) {
    }

    void readProperties(java.util.Properties p) {
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return em;
    }
}
