package org.jreserve.triangle.widget;

import java.awt.BorderLayout;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jreserve.resources.textfieldfilters.IntegerFilter;
import org.openide.util.Exceptions;

/**
 *
 * @author Peter Decsi
 */
public class AxisGeometryPanel extends javax.swing.JPanel implements ChangeListener {
    
    public final static String PROPERTY_FROM = "FROM DATE";
    public final static String PROPERTY_PERIODS = "PERIODS";
    public final static String PROPERTY_MONTHS = "MONTHS";

    private final static int DEFAULT_PERIODS = 1;
    private final static int DEFAULT_STEPS = 12;
    
    private SpinnerNumberModel periodModel = new SpinnerNumberModel(DEFAULT_PERIODS, 1, Integer.MAX_VALUE, 1);
    private SpinnerNumberModel monthModel = new SpinnerNumberModel(DEFAULT_STEPS, 1, Integer.MAX_VALUE, 1);
    
    public AxisGeometryPanel() {
        initComponents();
    }
    
    @Override
    public void setEnabled(boolean enabled) {
        fromSpinner.setEnabled(enabled);
        periodSpinner.setEnabled(enabled);
        monthsSpinner.setEnabled(enabled);
    }
    
    public void setFromDateEnabled(boolean enabled) {
        fromSpinner.setEnabled(enabled);
    }
    
    public Date getFromDate() {
        return fromSpinner.getDate();
    }
    
    public String getFromDateAsString() {
        return fromSpinner.getText();
    }
    
    public void setFromDate(Date date) {
        fromSpinner.setValue(date);
    }
    
    public void setPeriodsEnabled(boolean enabled) {
        periodSpinner.setEnabled(enabled);
    }
    
    public int getPeriods() {
        return periodModel.getNumber().intValue();
    }
    
    public void setPeriods(int periods) {
        periodModel.setValue(periods);
    }
    
    public void setMonthsEnabled(boolean enabled) {
        monthsSpinner.setEnabled(enabled);
    }
    
    public int getMonthPerStep() {
        return monthModel.getNumber().intValue();
    }
    
    public void setMonthPerStep(int months) {
        monthModel.setValue(months);
    }

    @Override
    public void stateChanged(ChangeEvent e) {
        Object source = e.getSource();
        if(fromSpinner == source) {
            setProperty(PROPERTY_FROM, fromSpinner.getValue());
        } else if(periodSpinner == source) {
            setProperty(PROPERTY_PERIODS, periodSpinner.getValue());
        } else if(monthsSpinner == source) {
            setProperty(PROPERTY_MONTHS, monthsSpinner.getValue());
        }
    }
    
    private void setProperty(String name, Object value) {
        putClientProperty(name, value);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        stepLabel = new javax.swing.JLabel();
        fromSpinner = new org.jreserve.resources.textfieldfilters.DateSpinner();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        periodSpinner = new javax.swing.JSpinner();
        monthsSpinner = new javax.swing.JSpinner();

        setLayout(new java.awt.GridBagLayout());

        fromLabel.setText(org.openide.util.NbBundle.getMessage(AxisGeometryPanel.class, "LBL.AxisGeometryPanel.Begin")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        add(fromLabel, gridBagConstraints);

        toLabel.setText(org.openide.util.NbBundle.getMessage(AxisGeometryPanel.class, "LBL.AxisGeometryPanel.Periods")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        add(toLabel, gridBagConstraints);

        stepLabel.setText(org.openide.util.NbBundle.getMessage(AxisGeometryPanel.class, "LBL.AxisGeometryPanel.Steps")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(stepLabel, gridBagConstraints);

        fromSpinner.addChangeListener(this);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(fromSpinner, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(filler1, gridBagConstraints);

        periodSpinner.setModel(periodModel);
        periodSpinner.setEditor(new IntegerSpinnerEditor(periodSpinner));
        periodSpinner.addChangeListener(this);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(periodSpinner, gridBagConstraints);

        monthsSpinner.setModel(monthModel);
        monthsSpinner.setEditor(new IntegerSpinnerEditor(monthsSpinner));
        monthsSpinner.addChangeListener(this);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.weightx = 1.0;
        add(monthsSpinner, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel fromLabel;
    private org.jreserve.resources.textfieldfilters.DateSpinner fromSpinner;
    private javax.swing.JSpinner monthsSpinner;
    private javax.swing.JSpinner periodSpinner;
    private javax.swing.JLabel stepLabel;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables
    
}
