/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jreserve.resources.layerexplorer;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.filesystems.FileUtil;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd = "-//org.jreserve.resources.layerexplorer//LayerExplorer//EN",
    autostore = false
)
@TopComponent.Description(
    preferredID = "LayerExplorerTopComponent",
    //iconBase="SET/PATH/TO/ICON/HERE", 
    persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(
    mode = "rightSlidingSide", 
    openAtStartup = true
)
@ActionID(
    category = "Window", 
    id = "org.jreserve.resources.layerexplorer.LayerExplorerTopComponent"
)
@ActionReference(
    path = "Menu/Window",
    position = 500
)
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_LayerExplorerAction",
    preferredID = "LayerExplorerTopComponent"
)
@Messages({
    "CTL_LayerExplorerAction=Layer Explorer",
    "CTL_LayerExplorerTopComponent=Layer Explorer"
})
public final class LayerExplorerTopComponent extends TopComponent implements ExplorerManager.Provider {

    private final static ExplorerManager em = new ExplorerManager();
    
    public LayerExplorerTopComponent() {
        initComponents();
        setName(Bundle.CTL_LayerExplorerTopComponent());
        initTree();
    }
    
    private void initTree() {
        //FileNode root = new FileNode(FileUtil.getConfigFile("jreserve"));
        FileNode root = new FileNode(FileUtil.getConfigFile(""));
        em.setRootContext(root);
        associateLookup(ExplorerUtils.createLookup(em, getActionMap()));
        beanTreeView1.setRootVisible(false);
    }
    
    @Override
    public ExplorerManager getExplorerManager() {
        return em;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beanTreeView1 = new org.openide.explorer.view.BeanTreeView();

        setLayout(new java.awt.BorderLayout());
        add(beanTreeView1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openide.explorer.view.BeanTreeView beanTreeView1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
